In [2]:
import pandas as pd
import numpy as np

In [3]:
"""
    numpy.concatenate()
"""

x = [1,2,3]
y = [4,5,6]
z = [7,8,9]

np.concatenate([x,y,z])
# vstack () : vertically
# hstack () : horizen

print(np.vstack([x, y, z]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
"""
    Pandas.concat()
"""

ser1 = pd.Series(['A','B','C'], index=[1, 2, 3])
ser2 = pd.Series(['D','E','F'], index=[4, 5, 6])

pd.concat([ser1, ser2])

# Simply concatenate the two Series objects
print(pd.concat([ser2, ser1]))

4    D
5    E
6    F
1    A
2    B
3    C
dtype: object


In [4]:
# make_df(): create a DataFrame object
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    
    return pd.DataFrame(data, ind)

make_df('ABC', [1,2])

A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [5]:
#Concatenate the two DataFrame objects

df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])

print(df1, '\n')
print(df2, '\n')

print(pd.concat([df1,df2]))

    A   B
1  A1  B1
2  A2  B2 

    A   B
3  A3  B3
4  A4  B4 

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [10]:
df3 = make_df('AB', [0,1])
df4 = make_df('CD', [0,1])

print(df3, '\n')
print(df4, '\n')

print(pd.concat([df3, df4], axis = 0))

    A   B
0  A0  B0
1  A1  B1 

    C   D
0  C0  D0
1  C1  D1 

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1


In [6]:
"""
    concate() Features
"""

# Case 1: Duplicate indices
x = make_df('AB', [0,1])
y = make_df('AB', [2,3])

y.index = x.index

print(x, '\n')
print(y, '\n')

print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1 

    A   B
0  A2  B2
1  A3  B3 

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [11]:
# Case 2: Catching duplications as errors

try:
    pd.concat([x,y], verify_integrity=True)
    
except ValueError as e:
    print("ValueError: ", e)

ValueError:  Indexes have overlapping values: Int64Index([0, 1, 2], dtype='int64')


In [13]:
# Case 3: Ignore the index:

print(pd.concat([x, y], ignore_index = True))

     A   B   C    D
0   A0  B0  C0  NaN
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B0  C0   D0
4  NaN  B1  C1   D1
5  NaN  B2  C2   D2


In [16]:
"""
    concat(): join options
"""

x = make_df('ABC', [1,2])
y = make_df('BCD', [3,4])

# default: outer join -> union

print(x, '\n')
print(y, '\n')

print(pd.concat([x, y], join='inner'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2 

    B   C   D
3  B3  C3  D3
4  B4  C4  D4 

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [18]:
"""
    Join operations
"""

# Prepare the two DataFrame objects
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})

df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                   'hire_date': [2004, 2008, 2012, 2014]})

print(df1, '\n')
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [19]:
# One-to-one joins
df3 = pd.merge(df1, df2)
print(df3)p

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [21]:
# Many-to-one joins
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                   'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3, '\n')
print(df4, '\n')

print(pd.merge(df3, df4)) #df3 = Left, df = right 

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014 

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve 

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


In [24]:
# Many-to-many joins

df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                             'Engineering','Engineering',
                             'HR', 'HR'],
                   'skills': ['math', 'spreadsheets', 'coding',
                             'linux', 'spreadsheets', 'oranization']})

print(df1, '\n')
print(df5, '\n')

print(pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR   oranization 

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR   oranization


In [26]:
# 'on' argument: use a common column as merge key

print(df1, '\n')
print(df2, '\n')

df1['age'] = pd.Series([20, 42, 37, 25])
df1['age'] = pd.Series([37, 20, 42, 25])

print(df1, '\n')
print(df2, '\n')

print(pd.merge(df1, df2, on='employee'))

  employee        group  age
0      Bob   Accounting   37
1     Jake  Engineering   20
2     Lisa  Engineering   42
3      Sue           HR   25 

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 

  employee        group  age
0      Bob   Accounting   37
1     Jake  Engineering   20
2     Lisa  Engineering   42
3      Sue           HR   25 

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 

  employee        group  age  hire_date
0      Bob   Accounting   37       2008
1     Jake  Engineering   20       2012
2     Lisa  Engineering   42       2004
3      Sue           HR   25       2014


In [30]:
# 'left on' and 'right_on' arguments:

df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'salary': [70000, 80000, 120000, 90000]})

print(df1, '\n')
print(df3, '\n')

print(pd.merge(df1, df3, left_on = 'employee', right_on = 'name'))

  employee        group  age
0      Bob   Accounting   37
1     Jake  Engineering   20
2     Lisa  Engineering   42
3      Sue           HR   25 

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000 

  employee        group  age  name  salary
0      Bob   Accounting   37   Bob   70000
1     Jake  Engineering   20  Jake   80000
2     Lisa  Engineering   42  Lisa  120000
3      Sue           HR   25   Sue   90000


In [31]:
# 'left_index' and 'right_index' arguments 

In [36]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

print(df1a, '\n')
print(df2a, '\n')

print(pd.merge(df1a, df2a, left_index = True, right_index = True))

                group  age
employee                  
Bob        Accounting   37
Jake      Engineering   20
Lisa      Engineering   42
Sue                HR   25 

          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014 

                group  age  hire_date
employee                             
Bob        Accounting   37       2008
Jake      Engineering   20       2012
Lisa      Engineering   42       2004
Sue                HR   25       2014
